{{ config(materialized='table') }}

SELECT
    MD5(CONCAT(COMPANY_ID, '||', COALESCE(METADATA_LOAD_TS::VARCHAR, 'INITIAL'))) AS COMPANY_SK,
    COMPANY_ID,
    TICKER,
    COMPANY_NAME,
    SECTOR,
    INDUSTRY,
    MARKET_CAP_BAND,
    COUNTRY,
    PRIMARY_EXCHANGE_ID,
    STATUS,
    LISTED_SINCE,
    UPDATED_AT,
    HASH_DIFF,
    COALESCE(METADATA_LOAD_TS, CURRENT_TIMESTAMP()) AS EFF_START_TS,
    '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFF_END_TS,
    TRUE AS IS_CURRENT,
    CURRENT_TIMESTAMP() AS DW_INSERT_TS
FROM {{ ref('stg_companies') }}
