{{ config(materialized='table') }}

WITH date_spine AS (
    -- Generates daily dates for year 2026
    SELECT 
        DATEADD(day, SEQ4(), '2026-01-01'::DATE) AS DATE_DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 365))
)

SELECT
    TO_NUMBER(TO_CHAR(DATE_DAY, 'YYYYMMDD')) AS DATE_SK,
    DATE_DAY AS CALENDAR_DATE,
    EXTRACT(YEAR FROM DATE_DAY) AS YEAR,
    EXTRACT(MONTH FROM DATE_DAY) AS MONTH,
    TO_CHAR(DATE_DAY, 'Mon') AS MONTH_NAME,
    EXTRACT(QUARTER FROM DATE_DAY) AS QUARTER,
    EXTRACT(DAY FROM DATE_DAY) AS DAY_OF_MONTH,
    DAYNAME(DATE_DAY) AS DAY_NAME,
    EXTRACT(DAYOFWEEK FROM DATE_DAY) AS DAY_OF_WEEK,
    CASE WHEN EXTRACT(DAYOFWEEK FROM DATE_DAY) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM date_spine
