-- ==============================================================================
-- Stock Analytics Platform (Multi-Exchange) - Initial Setup
-- ==============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE STOCK_ANALYTICS_WH;

-- 1. Create Database
CREATE DATABASE IF NOT EXISTS STOCK_ANALYTICS_DB
    COMMENT = 'Database for Multi-Exchange Stock Analytics Platform';

USE DATABASE STOCK_ANALYTICS_DB;

-- 2. Create Schemas (Medallion Architecture + Ops + Semantic)
CREATE SCHEMA IF NOT EXISTS BRONZE
    COMMENT = 'Raw data ingestion layer loaded via Snowpipe';

CREATE SCHEMA IF NOT EXISTS SILVER
    COMMENT = 'Cleaned, typed, and standardized layer transformed by dbt';

CREATE SCHEMA IF NOT EXISTS GOLD
    COMMENT = 'Star schema layer with dimensions and facts transformed by dbt';

CREATE SCHEMA IF NOT EXISTS OPS
    COMMENT = 'Operational audit logs and rejected records';

CREATE SCHEMA IF NOT EXISTS SEMANTIC
    COMMENT = 'Business-ready semantic views for Streamlit and analytics';

-- 3. Create File Format for CSVs
CREATE OR REPLACE FILE FORMAT BRONZE.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- 4. Create Snowflake Internal Stage
CREATE OR REPLACE STAGE BRONZE.STOCK_STAGE
    FILE_FORMAT = BRONZE.CSV_FORMAT
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Internal stage for landing CSV feeds: exchanges, companies, prices, corporate actions';

-- ==============================================================================
-- 5. Create Bronze / RAW Tables
-- ==============================================================================

-- 5.1 RAW_EXCHANGES
CREATE OR REPLACE TABLE BRONZE.RAW_EXCHANGES (
    EXCHANGE_ID VARCHAR,
    EXCHANGE_CODE VARCHAR,
    COUNTRY VARCHAR,
    CURRENCY VARCHAR,
    TIMEZONE VARCHAR,
    MARKET_TYPE VARCHAR,
    STATUS VARCHAR,
    ESTABLISHED_DATE VARCHAR,
    UPDATED_AT VARCHAR,
    METADATA_LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA_FILE_NAME VARCHAR,
    METADATA_ROW_NUMBER NUMBER
);

-- 5.2 RAW_COMPANIES
CREATE OR REPLACE TABLE BRONZE.RAW_COMPANIES (
    COMPANY_ID VARCHAR,
    TICKER VARCHAR,
    COMPANY_NAME VARCHAR,
    SECTOR VARCHAR,
    INDUSTRY VARCHAR,
    MARKET_CAP_BAND VARCHAR,
    COUNTRY VARCHAR,
    PRIMARY_EXCHANGE_ID VARCHAR,
    STATUS VARCHAR,
    LISTED_SINCE VARCHAR,
    UPDATED_AT VARCHAR,
    METADATA_LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA_FILE_NAME VARCHAR,
    METADATA_ROW_NUMBER NUMBER
);

-- 5.3 RAW_PRICES_DAILY
CREATE OR REPLACE TABLE BRONZE.RAW_PRICES_DAILY (
    PRICE_ID VARCHAR,
    TRADE_DATE VARCHAR,
    COMPANY_ID VARCHAR,
    EXCHANGE_ID VARCHAR,
    OPEN VARCHAR,
    HIGH VARCHAR,
    LOW VARCHAR,
    CLOSE VARCHAR,
    ADJ_CLOSE VARCHAR,
    VOLUME VARCHAR,
    VWAP VARCHAR,
    UPDATED_AT VARCHAR,
    METADATA_LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA_FILE_NAME VARCHAR,
    METADATA_ROW_NUMBER NUMBER
);

-- 5.4 RAW_CORPORATE_ACTIONS
CREATE OR REPLACE TABLE BRONZE.RAW_CORPORATE_ACTIONS (
    ACTION_ID VARCHAR,
    COMPANY_ID VARCHAR,
    TICKER VARCHAR,
    ACTION_TYPE VARCHAR,
    EX_DATE VARCHAR,
    RECORD_DATE VARCHAR,
    PAY_DATE VARCHAR,
    ACTION_VALUE VARCHAR,
    RATIO VARCHAR,
    CURRENCY VARCHAR,
    STATUS VARCHAR,
    UPDATED_AT VARCHAR,
    METADATA_LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    METADATA_FILE_NAME VARCHAR,
    METADATA_ROW_NUMBER NUMBER
);

-- ==============================================================================
-- 6. Create OPS Audit & Rejects Tables
-- ==============================================================================

CREATE OR REPLACE TABLE OPS.LOAD_AUDIT (
    BATCH_ID VARCHAR,
    ENTITY_NAME VARCHAR,
    FILE_NAME VARCHAR,
    ROWS_LOADED NUMBER,
    STATUS VARCHAR,
    LOAD_START_TIME TIMESTAMP_NTZ,
    LOAD_END_TIME TIMESTAMP_NTZ,
    ERROR_MESSAGE VARCHAR
);

CREATE OR REPLACE TABLE OPS.REJECTS (
    REJECT_ID VARCHAR DEFAULT UUID_STRING(),
    ENTITY_NAME VARCHAR,
    FILE_NAME VARCHAR,
    ROW_NUMBER NUMBER,
    ERROR_MESSAGE VARCHAR,
    RECORD_DATA VARCHAR,
    REJECT_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ==============================================================================
-- 7. Create Snowpipes (One pipe per entity)
-- ==============================================================================

-- Pipe 1: Exchanges
CREATE OR REPLACE PIPE BRONZE.PIPE_EXCHANGES
    AUTO_INGEST = FALSE
    AS
    COPY INTO BRONZE.RAW_EXCHANGES (
        EXCHANGE_ID, EXCHANGE_CODE, COUNTRY, CURRENCY, TIMEZONE,
        MARKET_TYPE, STATUS, ESTABLISHED_DATE, UPDATED_AT,
        METADATA_LOAD_TS, METADATA_FILE_NAME, METADATA_ROW_NUMBER
    )
    FROM (
        SELECT 
            s.$1, s.$2, s.$3, s.$4, s.$5, 
            s.$6, s.$7, s.$8, s.$9,
            CURRENT_TIMESTAMP(),
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER
        FROM @BRONZE.STOCK_STAGE/exchanges/ s
    )
    FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FORMAT')
    ON_ERROR = 'CONTINUE';

-- Pipe 2: Companies
CREATE OR REPLACE PIPE BRONZE.PIPE_COMPANIES
    AUTO_INGEST = FALSE
    AS
    COPY INTO BRONZE.RAW_COMPANIES (
        COMPANY_ID, TICKER, COMPANY_NAME, SECTOR, INDUSTRY,
        MARKET_CAP_BAND, COUNTRY, PRIMARY_EXCHANGE_ID, STATUS, LISTED_SINCE, UPDATED_AT,
        METADATA_LOAD_TS, METADATA_FILE_NAME, METADATA_ROW_NUMBER
    )
    FROM (
        SELECT 
            s.$1, s.$2, s.$3, s.$4, s.$5,
            s.$6, s.$7, s.$8, s.$9, s.$10, s.$11,
            CURRENT_TIMESTAMP(),
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER
        FROM @BRONZE.STOCK_STAGE/companies/ s
    )
    FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FORMAT')
    ON_ERROR = 'CONTINUE';

-- Pipe 3: Daily Prices
CREATE OR REPLACE PIPE BRONZE.PIPE_PRICES_DAILY
    AUTO_INGEST = FALSE
    AS
    COPY INTO BRONZE.RAW_PRICES_DAILY (
        PRICE_ID, TRADE_DATE, COMPANY_ID, EXCHANGE_ID,
        OPEN, HIGH, LOW, CLOSE, ADJ_CLOSE, VOLUME, VWAP, UPDATED_AT,
        METADATA_LOAD_TS, METADATA_FILE_NAME, METADATA_ROW_NUMBER
    )
    FROM (
        SELECT 
            s.$1, s.$2, s.$3, s.$4,
            s.$5, s.$6, s.$7, s.$8, s.$9, s.$10, s.$11, s.$12,
            CURRENT_TIMESTAMP(),
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER
        FROM @BRONZE.STOCK_STAGE/prices_daily/ s
    )
    FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FORMAT')
    ON_ERROR = 'CONTINUE';

-- Pipe 4: Corporate Actions
CREATE OR REPLACE PIPE BRONZE.PIPE_CORPORATE_ACTIONS
    AUTO_INGEST = FALSE
    AS
    COPY INTO BRONZE.RAW_CORPORATE_ACTIONS (
        ACTION_ID, COMPANY_ID, TICKER, ACTION_TYPE,
        EX_DATE, RECORD_DATE, PAY_DATE, ACTION_VALUE, RATIO, CURRENCY, STATUS, UPDATED_AT,
        METADATA_LOAD_TS, METADATA_FILE_NAME, METADATA_ROW_NUMBER
    )
    FROM (
        SELECT 
            s.$1, s.$2, s.$3, s.$4,
            s.$5, s.$6, s.$7, s.$8, s.$9, s.$10, s.$11, s.$12,
            CURRENT_TIMESTAMP(),
            METADATA$FILENAME,
            METADATA$FILE_ROW_NUMBER
        FROM @BRONZE.STOCK_STAGE/corporate_actions/ s
    )
    FILE_FORMAT = (FORMAT_NAME = 'BRONZE.CSV_FORMAT')
    ON_ERROR = 'CONTINUE';

-- ==============================================================================
-- 8. Basic RBAC Roles (Least Privilege)
-- ==============================================================================

CREATE ROLE IF NOT EXISTS ROLE_INGEST COMMENT = 'Role for data ingestion tasks';
CREATE ROLE IF NOT EXISTS ROLE_ETL COMMENT = 'Role for transformation pipelines (dbt)';
CREATE ROLE IF NOT EXISTS ROLE_ANALYST COMMENT = 'Role for analysts querying Gold and Semantic layers';
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT COMMENT = 'Role for Streamlit application read-only access';

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE STOCK_ANALYTICS_WH TO ROLE ROLE_INGEST;
GRANT USAGE ON WAREHOUSE STOCK_ANALYTICS_WH TO ROLE ROLE_ETL;
GRANT USAGE ON WAREHOUSE STOCK_ANALYTICS_WH TO ROLE ROLE_ANALYST;
GRANT USAGE ON WAREHOUSE STOCK_ANALYTICS_WH TO ROLE ROLE_APP_STREAMLIT;

-- Grant database usage
GRANT USAGE ON DATABASE STOCK_ANALYTICS_DB TO ROLE ROLE_INGEST;
GRANT USAGE ON DATABASE STOCK_ANALYTICS_DB TO ROLE ROLE_ETL;
GRANT USAGE ON DATABASE STOCK_ANALYTICS_DB TO ROLE ROLE_ANALYST;
GRANT USAGE ON DATABASE STOCK_ANALYTICS_DB TO ROLE ROLE_APP_STREAMLIT;

-- Ingestion role accesses Bronze and Ops
GRANT USAGE, CREATE STAGE, CREATE PIPE, CREATE TABLE ON SCHEMA BRONZE TO ROLE ROLE_INGEST;
GRANT ALL ON SCHEMA OPS TO ROLE ROLE_INGEST;

-- ETL role accesses Bronze (read), Silver (full), Gold (full)
GRANT USAGE ON SCHEMA BRONZE TO ROLE ROLE_ETL;
GRANT SELECT ON ALL TABLES IN SCHEMA BRONZE TO ROLE ROLE_ETL;
GRANT ALL ON SCHEMA SILVER TO ROLE ROLE_ETL;
GRANT ALL ON SCHEMA GOLD TO ROLE ROLE_ETL;

-- Analyst & Streamlit roles access Semantic and Gold (read-only)
GRANT USAGE ON SCHEMA GOLD TO ROLE ROLE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA SEMANTIC TO ROLE ROLE_ANALYST;
GRANT USAGE ON SCHEMA SEMANTIC TO ROLE ROLE_APP_STREAMLIT;
