{{ config(materialized='view') }}

SELECT
    f.SECTOR,
    f.EXCHANGE_CODE,
    COUNT(DISTINCT f.TICKER) AS TOTAL_COMPANIES,
    COUNT(f.PRICE_FACT_SK) AS TOTAL_TRADING_RECORDS,
    ROUND(AVG(f.CLOSE_PRICE), 2) AS AVG_CLOSE_PRICE,
    ROUND(AVG(f.DAILY_RETURN_PCT), 4) AS AVG_DAILY_RETURN_PCT,
    ROUND(AVG(f.VOLATILITY_20D), 4) AS AVG_VOLATILITY_20D,
    SUM(f.VOLUME) AS TOTAL_VOLUME,
    ROUND(SUM(f.VOLUME * f.VWAP) / NULLIF(SUM(f.VOLUME), 0), 2) AS SECTOR_VWAP
FROM {{ ref('fact_daily_price') }} f
GROUP BY f.SECTOR, f.EXCHANGE_CODE
