{{ config(materialized='view') }}

SELECT
    TRIM(COMPANY_ID) AS COMPANY_ID,
    UPPER(TRIM(TICKER)) AS TICKER,
    TRIM(COMPANY_NAME) AS COMPANY_NAME,
    TRIM(SECTOR) AS SECTOR,
    TRIM(INDUSTRY) AS INDUSTRY,
    TRIM(MARKET_CAP_BAND) AS MARKET_CAP_BAND,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(PRIMARY_EXCHANGE_ID) AS PRIMARY_EXCHANGE_ID,
    UPPER(TRIM(STATUS)) AS STATUS,
    TRY_TO_DATE(LISTED_SINCE) AS LISTED_SINCE,
    TRY_TO_TIMESTAMP_NTZ(UPDATED_AT) AS UPDATED_AT,
    MD5(CONCAT_WS('||',
        COALESCE(TRIM(COMPANY_NAME), ''),
        COALESCE(TRIM(SECTOR), ''),
        COALESCE(TRIM(INDUSTRY), ''),
        COALESCE(TRIM(MARKET_CAP_BAND), ''),
        COALESCE(TRIM(PRIMARY_EXCHANGE_ID), ''),
        COALESCE(UPPER(TRIM(STATUS)), ''),
        COALESCE(TRIM(COUNTRY), '')
    )) AS HASH_DIFF,
    METADATA_LOAD_TS,
    METADATA_FILE_NAME
FROM {{ source('bronze', 'raw_companies') }}
