{{ config(materialized='view') }}

SELECT
    TRIM(EXCHANGE_ID) AS EXCHANGE_ID,
    UPPER(TRIM(EXCHANGE_CODE)) AS EXCHANGE_CODE,
    TRIM(COUNTRY) AS COUNTRY,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    TRIM(TIMEZONE) AS TIMEZONE,
    UPPER(TRIM(MARKET_TYPE)) AS MARKET_TYPE,
    UPPER(TRIM(STATUS)) AS STATUS,
    TRY_TO_DATE(ESTABLISHED_DATE) AS ESTABLISHED_DATE,
    TRY_TO_TIMESTAMP_NTZ(UPDATED_AT) AS UPDATED_AT,
    METADATA_LOAD_TS,
    METADATA_FILE_NAME
FROM {{ source('bronze', 'raw_exchanges') }}
