{{ config(materialized='view') }}

SELECT
    TRIM(ACTION_ID) AS ACTION_ID,
    TRIM(COMPANY_ID) AS COMPANY_ID,
    UPPER(TRIM(TICKER)) AS TICKER,
    UPPER(TRIM(ACTION_TYPE)) AS ACTION_TYPE,
    TRY_TO_DATE(EX_DATE) AS EX_DATE,
    TRY_TO_DATE(RECORD_DATE) AS RECORD_DATE,
    TRY_TO_DATE(PAY_DATE) AS PAY_DATE,
    TRY_TO_DECIMAL(ACTION_VALUE, 12, 4) AS ACTION_VALUE,
    NULLIF(TRIM(RATIO), '') AS RATIO,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    UPPER(TRIM(STATUS)) AS STATUS,
    TRY_TO_TIMESTAMP_NTZ(UPDATED_AT) AS UPDATED_AT,
    METADATA_LOAD_TS,
    METADATA_FILE_NAME
FROM {{ source('bronze', 'raw_corporate_actions') }}
